[pytest]
pythonpath = .

markers =
    frontend_integration: vollständige Frontend-Integrationstests mit Dash/Selenium

filterwarnings =
    ignore:HTTPResponse.getheader\(\) is deprecated:DeprecationWarning